#!/bin/bash
set -euo pipefail

# ============================================================================
# Dashboard Server Setup — Interactive Bootstrap
# Run this from your laptop to provision the centralized dashboard in AWS
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"
CONFIGS_DIR="$PROJECT_ROOT/configs"
TFVARS_FILE="$CONFIGS_DIR/dashboard.tfvars"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

echo ""
echo "============================================"
echo "  Red Team Dashboard — Server Setup"
echo "============================================"
echo ""

# --- Prerequisites ---
info "Checking prerequisites..."

command -v aws >/dev/null 2>&1 || error "AWS CLI not found. Install: https://aws.amazon.com/cli/"
command -v terraform >/dev/null 2>&1 || error "Terraform not found. Install: https://terraform.io"
command -v ssh >/dev/null 2>&1 || error "SSH client not found."
command -v rsync >/dev/null 2>&1 || error "rsync not found."

# Verify AWS credentials
info "Verifying AWS credentials..."
AWS_IDENTITY=$(aws sts get-caller-identity 2>/dev/null) || error "AWS credentials not configured. Run: aws configure"
AWS_ACCOUNT=$(echo "$AWS_IDENTITY" | jq -r '.Account')
success "AWS account: $AWS_ACCOUNT"

# --- Auto-detect values ---

# SSH key — check common locations across macOS, Linux, Windows (WSL/Git Bash)
SSH_KEY_PATH=""
for candidate in \
    ~/.ssh/id_ed25519.pub \
    ~/.ssh/id_rsa.pub \
    ~/.ssh/id_ecdsa.pub \
    /mnt/c/Users/$USER/.ssh/id_ed25519.pub \
    /mnt/c/Users/$USER/.ssh/id_rsa.pub \
    "$USERPROFILE/.ssh/id_ed25519.pub" \
    "$USERPROFILE/.ssh/id_rsa.pub"; do
    if [ -f "$candidate" 2>/dev/null ]; then
        SSH_KEY_PATH="$candidate"
        break
    fi
done

# Public IP
DETECTED_IP=$(curl -4 -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "")

# AWS region
DETECTED_REGION=$(aws configure get region 2>/dev/null || echo "eu-central-1")

# Operator name
DETECTED_USER=$(whoami)

# --- Prompt for values ---
echo ""
info "Configure your dashboard server:"
echo ""

# SSH key
if [ -n "$SSH_KEY_PATH" ]; then
    success "Auto-detected SSH key: $SSH_KEY_PATH"
fi
read -rp "SSH public key path (press Enter to use detected) [$SSH_KEY_PATH]: " INPUT_KEY
SSH_KEY_PATH="${INPUT_KEY:-$SSH_KEY_PATH}"
[ -f "$SSH_KEY_PATH" ] || error "SSH public key not found: $SSH_KEY_PATH"
SSH_KEY_CONTENT=$(cat "$SSH_KEY_PATH")

# Validate SSH key format
if ! echo "$SSH_KEY_CONTENT" | grep -qE '^ssh-(ed25519|rsa|ecdsa-sha2-nistp[0-9]+) [A-Za-z0-9+/=]+'; then
    error "Invalid SSH public key format in $SSH_KEY_PATH"
fi
success "SSH key: $SSH_KEY_PATH"

# Operator name
read -rp "Your operator name [$DETECTED_USER]: " INPUT_USER
OPERATOR_NAME="${INPUT_USER:-$DETECTED_USER}"

# Validate operator name (must be valid Linux username)
if ! echo "$OPERATOR_NAME" | grep -qE '^[a-z][a-z0-9_-]{0,31}$'; then
    error "Invalid operator name. Must be lowercase, start with letter, 1-32 chars, only a-z 0-9 _ -"
fi

# Public IP
read -rp "Your public IP [$DETECTED_IP]: " INPUT_IP
OPERATOR_IP="${INPUT_IP:-$DETECTED_IP}"
[ -n "$OPERATOR_IP" ] || error "Could not detect public IP. Enter manually."
success "Your IP: $OPERATOR_IP"

# Region
read -rp "AWS region [$DETECTED_REGION]: " INPUT_REGION
AWS_REGION="${INPUT_REGION:-$DETECTED_REGION}"

# Second operator (optional)
echo ""
read -rp "Second operator SSH public key (paste full key, or press Enter to skip): " OP2_KEY
OP2_NAME=""
OP2_IP=""
if [ -n "$OP2_KEY" ]; then
    # Validate second operator's key
    if ! echo "$OP2_KEY" | grep -qE '^ssh-(ed25519|rsa|ecdsa-sha2-nistp[0-9]+) [A-Za-z0-9+/=]+'; then
        error "Invalid SSH public key format for second operator"
    fi
    read -rp "Second operator name: " OP2_NAME
    if ! echo "$OP2_NAME" | grep -qE '^[a-z][a-z0-9_-]{0,31}$'; then
        error "Invalid operator name. Must be lowercase, start with letter, 1-32 chars, only a-z 0-9 _ -"
    fi
    read -rp "Second operator IP: " OP2_IP
    [ -n "$OP2_IP" ] || error "Operator IP required"
fi

# --- Generate tfvars ---
echo ""
info "Generating $TFVARS_FILE..."

mkdir -p "$CONFIGS_DIR"
cat > "$TFVARS_FILE" <<EOF
# Dashboard Server Configuration
# Generated by setup-dashboard.sh on $(date)

enable_dashboard_server = true
aws_region              = "$AWS_REGION"

dashboard_allowed_ips = [
  "$OPERATOR_IP/32",
$([ -n "$OP2_IP" ] && echo "  \"$OP2_IP/32\",")
]

operator_ssh_public_keys = {
  "$OPERATOR_NAME" = "$SSH_KEY_CONTENT"
$([ -n "$OP2_KEY" ] && echo "  \"$OP2_NAME\" = \"$OP2_KEY\"")
}
EOF

success "Generated: $TFVARS_FILE"

# --- Terraform ---
echo ""
info "Initializing Terraform..."
cd "$TERRAFORM_DIR"
terraform init

info "Planning dashboard server..."
terraform plan -var-file="$TFVARS_FILE" -target=module.dashboard_server -out=dashboard.tfplan

echo ""
read -rp "Apply this plan? (yes/no): " CONFIRM
[ "$CONFIRM" = "yes" ] || { warn "Aborted."; exit 0; }

info "Applying..."
terraform apply dashboard.tfplan
rm -f dashboard.tfplan

# Get the dashboard IP
DASHBOARD_IP=$(terraform output -raw dashboard_public_ip 2>/dev/null || echo "")
[ -n "$DASHBOARD_IP" ] || error "Could not determine dashboard IP from Terraform output"

success "Dashboard server provisioned: $DASHBOARD_IP"

# --- Wait for instance ---
echo ""
info "Waiting for instance to be ready (this may take 2-3 minutes)..."
INSTANCE_ID=$(terraform output -raw dashboard_instance_id 2>/dev/null || echo "")
if [ -n "$INSTANCE_ID" ]; then
    aws ec2 wait instance-status-ok --instance-ids "$INSTANCE_ID" --region "$AWS_REGION" 2>/dev/null || true
fi
# Extra wait for user_data to complete
sleep 30

# --- Rsync codebase ---
echo ""
info "Copying codebase to server..."
SSH_KEY_PRIVATE="${SSH_KEY_PATH%.pub}"
rsync -avz --progress \
    --exclude='uploads/' \
    --exclude='uploads_client/' \
    --exclude='uploads_tools/' \
    --exclude='local-only/' \
    --exclude='.git/' \
    --exclude='venv/' \
    --exclude='logs/' \
    --exclude='terraform.tfstate*' \
    --exclude='*.tfplan' \
    --exclude='.terraform/' \
    -e "ssh -i $SSH_KEY_PRIVATE -o StrictHostKeyChecking=accept-new" \
    "$PROJECT_ROOT/" \
    "$OPERATOR_NAME@$DASHBOARD_IP:/opt/redteam/"

success "Codebase synced"

# --- Remote setup ---
info "Setting up dashboard on server..."
ssh -i "$SSH_KEY_PRIVATE" -o StrictHostKeyChecking=accept-new "$OPERATOR_NAME@$DASHBOARD_IP" bash <<'REMOTE'
set -euo pipefail
cd /opt/redteam

# Create venv and install dependencies
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# Initialize Terraform with S3 backend
cd terraform
sudo terraform init -backend-config=/opt/redteam/backend.hcl

# Create systemd service
sudo tee /etc/systemd/system/dashboard.service > /dev/null <<'SERVICE'
[Unit]
Description=Red Team Dashboard
After=network.target

[Service]
Type=simple
User=dashboard
Group=dashboard
WorkingDirectory=/opt/redteam
ExecStart=/opt/redteam/venv/bin/python3 webapp/backend/app.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/opt/redteam
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SERVICE

sudo systemctl daemon-reload
sudo systemctl enable dashboard
sudo systemctl start dashboard
REMOTE

success "Dashboard service started"

# --- Done ---
echo ""
echo "============================================"
echo "  Dashboard Server Ready!"
echo "============================================"
echo ""
echo "  IP:       $DASHBOARD_IP"
echo "  Connect:  ssh -L 5000:localhost:5000 $OPERATOR_NAME@$DASHBOARD_IP"
echo "  Open:     http://localhost:5000"
echo ""
echo "  Next steps:"
echo "  1. SCP Cobalt Strike archive:"
echo "     scp cobaltstrike.tar $OPERATOR_NAME@$DASHBOARD_IP:/opt/redteam/uploads/"
echo ""
if [ -n "$OP2_NAME" ]; then
echo "  2. Second operator connects:"
echo "     ssh -L 5000:localhost:5000 $OP2_NAME@$DASHBOARD_IP"
echo ""
fi
echo "============================================"
