#!/bin/bash
# =============================================================================
# GOAD Jumpbox Initialization Script (Without Cobalt Strike)
# =============================================================================
# This script sets up the jumpbox for GOAD lab management
# For GOAD-only mode with CS, use install_cobalt_strike.sh instead
# =============================================================================

set -e

USERNAME="${username}"

# Logging
LOG_FILE="/var/log/jumpbox-init.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "=============================================="
echo "GOAD Jumpbox Initialization"
echo "Started: $(date)"
echo "=============================================="

# Wait for cloud-init
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
    echo "Waiting for cloud-init..."
    sleep 5
done

# =============================================================================
# 1. System Updates
# =============================================================================
echo "[1/7] Updating system..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# =============================================================================
# 2. Install Required Packages
# =============================================================================
echo "[2/7] Installing packages..."
apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    ansible \
    git \
    curl \
    wget \
    unzip \
    sshpass \
    net-tools \
    htop \
    tmux \
    vim \
    jq \
    nmap \
    dnsutils \
    ldap-utils \
    krb5-user \
    smbclient \
    libkrb5-dev \
    libssl-dev \
    libffi-dev \
    python3-dev \
    build-essential

# =============================================================================
# 3. Configure User
# =============================================================================
echo "[3/7] Configuring user..."

# Rename ubuntu user if different username specified
if [ "$USERNAME" != "ubuntu" ] && [ "$USERNAME" != "" ]; then
    if id "ubuntu" &>/dev/null; then
        usermod -l "$USERNAME" ubuntu
        usermod -d "/home/$USERNAME" -m "$USERNAME"
        sed -i "s/ubuntu/$USERNAME/" /etc/sudoers.d/90-cloud-init-users 2>/dev/null || true
        echo "User renamed to: $USERNAME"
    fi
fi

# =============================================================================
# 4. Install Python Tools
# =============================================================================
echo "[4/7] Installing Python tools..."

pip3 install --upgrade pip
pip3 install \
    impacket \
    bloodhound \
    ldap3 \
    pycryptodome \
    pyasn1 \
    certipy-ad \
    coercer \
    pywinrm \
    ansible-core

# =============================================================================
# 5. Clone GOAD Repository
# =============================================================================
echo "[5/7] Cloning GOAD repository..."

# Create directories
mkdir -p /opt/goad
mkdir -p /opt/tools

# Clone the official GOAD repository for Ansible playbooks
if [ ! -d "/opt/goad-ansible/.git" ]; then
    git clone --depth 1 https://github.com/Orange-Cyberdefense/GOAD.git /opt/goad-ansible
    echo "GOAD repository cloned successfully"
else
    echo "GOAD repository already exists, pulling latest..."
    cd /opt/goad-ansible && git pull || true
fi

# Install GOAD Ansible requirements
if [ -f "/opt/goad-ansible/ansible/requirements.yml" ]; then
    echo "Installing GOAD Ansible requirements..."
    ansible-galaxy install -r /opt/goad-ansible/ansible/requirements.yml --force || true
    ansible-galaxy collection install -r /opt/goad-ansible/ansible/requirements.yml --force || true
fi

# Set ownership
chown -R ubuntu:ubuntu /opt/goad-ansible
chown -R ubuntu:ubuntu /opt/goad
chown -R ubuntu:ubuntu /opt/tools

# =============================================================================
# 6. Create Ansible Inventory for AWS
# =============================================================================
echo "[6/7] Creating Ansible inventory..."

# Create inventory directory
mkdir -p /opt/goad/inventory

# Create AWS-specific inventory file
cat > /opt/goad/inventory/hosts << 'INVENTORY'
# GOAD AWS Inventory
# Generated by jumpbox initialization script
# Update IPs based on your deployment

[all:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_port=5985

[dc]
dc01 ansible_host=192.168.56.10

[server]
# Add additional servers here based on lab type

[dvwa]
# Optional DVWA server

[elk]
# Optional ELK server
INVENTORY

echo "Inventory template created at /opt/goad/inventory/hosts"

# =============================================================================
# 7. Create Helper Scripts
# =============================================================================
echo "[7/7] Creating helper scripts..."

# Script to check lab status
cat > /opt/goad/check-lab.sh << 'EOF'
#!/bin/bash
echo "=== GOAD Lab Status ==="
echo ""
echo "Checking connectivity to lab VMs..."
for ip in 10 11 12 20 21 22 23; do
    ping -c 1 -W 1 192.168.56.$ip > /dev/null 2>&1 && echo "192.168.56.$ip: UP" || echo "192.168.56.$ip: DOWN"
done
echo ""
echo "=== WinRM Connectivity ==="
for ip in 10 11 12 20 21 22 23; do
    nc -z -w 2 192.168.56.$ip 5985 2>/dev/null && echo "192.168.56.$ip:5985 (WinRM): OPEN" || true
done
echo ""
echo "=== DNS Resolution ==="
nslookup sevenkingdoms.local 192.168.56.10 2>/dev/null || echo "DNS not configured yet"
EOF
chmod +x /opt/goad/check-lab.sh

# Script to run Ansible provisioning
cat > /opt/goad/provision.sh << 'EOF'
#!/bin/bash
echo "=== GOAD Ansible Provisioning ==="
echo "This will configure Active Directory on the lab VMs"
echo "This process takes 30-60 minutes"
echo ""
echo "GOAD Ansible playbooks are in: /opt/goad-ansible/ansible/"
echo ""
echo "Steps to provision:"
echo "  1. Update /opt/goad/inventory/hosts with correct passwords"
echo "  2. cd /opt/goad-ansible/ansible"
echo "  3. Run the appropriate playbook for your lab type:"
echo ""
echo "     For GOAD-Mini:"
echo "       ansible-playbook -i /opt/goad/inventory/hosts goad.yml -l dc01"
echo ""
echo "     For full provisioning (all VMs):"
echo "       ansible-playbook -i /opt/goad/inventory/hosts goad.yml"
echo ""
echo "Note: Ensure Windows VMs are fully booted and WinRM is accessible first."
echo "Use /opt/goad/check-lab.sh to verify connectivity."
EOF
chmod +x /opt/goad/provision.sh

# Script to update inventory with actual passwords
cat > /opt/goad/update-inventory.sh << 'EOF'
#!/bin/bash
# Update this script with actual VM passwords from Terraform output
# Then run it to update the inventory

INVENTORY_FILE="/opt/goad/inventory/hosts"

if [ -z "$1" ]; then
    echo "Usage: $0 <admin_password>"
    echo "This will update the inventory with the provided password"
    exit 1
fi

PASSWORD="$1"

# Add password to inventory
if ! grep -q "ansible_password" "$INVENTORY_FILE"; then
    sed -i "/\[all:vars\]/a ansible_password=$PASSWORD" "$INVENTORY_FILE"
    echo "Password added to inventory"
else
    sed -i "s/ansible_password=.*/ansible_password=$PASSWORD/" "$INVENTORY_FILE"
    echo "Password updated in inventory"
fi

echo "Inventory updated. You can now run provisioning."
EOF
chmod +x /opt/goad/update-inventory.sh

# =============================================================================
# Complete
# =============================================================================
echo ""
echo "=============================================="
echo "GOAD Jumpbox Initialization Complete!"
echo "Finished: $(date)"
echo "=============================================="
echo ""
echo "Useful directories:"
echo "  /opt/goad         - GOAD management scripts and inventory"
echo "  /opt/goad-ansible - Official GOAD Ansible playbooks"
echo "  /opt/tools        - Red team tools"
echo ""
echo "Next steps:"
echo "  1. Check lab status:     /opt/goad/check-lab.sh"
echo "  2. Update inventory:     /opt/goad/update-inventory.sh <password>"
echo "  3. Run provisioning:     /opt/goad/provision.sh (for instructions)"
echo ""

touch /opt/goad/.init-complete

